# Generated by Django 4.2 on 2023-04-27 06:09

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=web.models.get_file_upload_path),
        ),
    ]
